import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

/**
 * PRODUCTION-GRADE STYLE PROMPT
 * Derived from "Identity_Safety" and "Camera_Details" best practices.
 * This forces the model to behave like a physical camera engine and treat the face as sacred data.
 */
const GLOBAL_REALISM_PROMPT = `
  CRITICAL INSTRUCTION - IDENTITY PRESERVATION:
  - You MUST retain the EXACT facial features, skin tone, and identity of the person in the input image.
  - Do NOT generate a generic AI face. The goal is to "dress up" the specific person provided.
  - If the face is slightly blurry in the input, sharpen it subtly, but do NOT alter the bone structure, eyes, or nose shape.
  - Maintain the subject's gaze and expression unless specified otherwise.
  
  PHOTOGRAPHIC PHYSICS & QUALITY:
  - TEXTURE: The output must look like a raw 8K photograph. Skin must have pores and natural texture. NO "smooth" or "waxy" AI skin.
  - LIGHTING: Relight the subject's face to match the new environment (e.g., if the scene is sunset, add warm light to the face). The lighting on the face must look physically accurate.
  - COMPOSITION: Ensure the head connects naturally to the new body (neck width, skin tone matching).
  - CAMERA: Simulate a Sony A7R IV with an 85mm G Master lens. f/1.8 aperture for depth.
`;

/**
 * Uses Gemini 2.5 Flash Image to edit the user's photo.
 */
export const transformUserImage = async (
  base64Image: string,
  promptInstruction: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  try {
    // Remove data URL prefix
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg);base64,/, "");

    const model = 'gemini-2.5-flash-image'; 

    // Structure the prompt using the "Layered JSON-Logic" approach from the examples
    const fullPrompt = `
      OBJECTIVE: Create a photorealistic professional portrait of the user provided in the image.

      ${GLOBAL_REALISM_PROMPT}

      SCENE & ATTIRE SPECIFICATIONS:
      ${promptInstruction}
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          },
          {
            text: fullPrompt
          }
        ]
      }
    });

    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
        const parts = candidates[0].content.parts;
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/jpeg;base64,${part.inlineData.data}`;
            }
        }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};