import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

/**
 * NATURAL DOCUMENTARY STYLE PROMPT
 * Optimized for authentic, candid workplace photos that preserve the user's exact identity.
 */
const GLOBAL_REALISM_PROMPT = `
  CRITICAL - IDENTITY PRESERVATION (HIGHEST PRIORITY):
  - You MUST keep the person's EXACT face, facial features, bone structure, skin tone, and expression.
  - Do NOT change, alter, or "improve" their face in any way.
  - Do NOT smooth skin, remove blemishes, or beautify. Keep all natural skin texture, pores, freckles, and imperfections.
  - The person in the output MUST be immediately recognizable as the same person from the input photo.
  - If the person has glasses, facial hair, distinctive features - KEEP THEM EXACTLY.
  
  PHOTO STYLE - NATURAL & AUTHENTIC:
  - This should look like a real photo taken at an actual workplace by a coworker with a regular camera or phone.
  - Documentary-style photography. Candid and genuine, NOT a professional photoshoot.
  - Natural and relaxed, NOT posed or staged.
  - Think: "Real moment captured during a normal workday" NOT "Corporate headshot" or "Stock photography".
  
  COMPOSITION - CASUAL & NATURAL:
  - Show the person from chest-up or waist-up in their work environment.
  - Natural framing - can be slightly off-center, doesn't need to be perfectly composed.
  - Include some of the background environment to show context.
  - Don't force perfect symmetry or formal posing.
  
  LIGHTING - SIMPLE & REALISTIC:
  - Use whatever lighting would naturally exist in that environment.
  - Office: regular fluorescent or window light
  - Outdoor: natural daylight or shade
  - Lab/Hospital: normal interior lighting
  - NO special photography lighting setups, NO dramatic effects.
  
  OVERALL FEEL:
  - Authentic workplace moment, like a photo for a company newsletter or employee directory.
  - Real, genuine, natural - NOT cinematic, NOT commercial, NOT artistic.
`;

/**
 * Uses Gemini 2.5 Flash Image to edit the user's photo.
 */
export const transformUserImage = async (
  base64Image: string,
  promptInstruction: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  try {
    // Remove data URL prefix
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg);base64,/, "");

    const model = 'gemini-2.5-flash-image';

    // Structure the prompt using the "Layered JSON-Logic" approach from the examples
    const fullPrompt = `
      OBJECTIVE: Create a photorealistic professional portrait of the user provided in the image.

      ${GLOBAL_REALISM_PROMPT}

      SCENE & ATTIRE SPECIFICATIONS:
      ${promptInstruction}
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          },
          {
            text: fullPrompt
          }
        ]
      }
    });

    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};